# From https://hub.docker.com/r/cypress/browsers/tags
FROM cypress/included:13.6.0

WORKDIR /opt/test

COPY ./tests/package.json package.json
COPY ./tests/package-lock.json package-lock.json
COPY ./tests/cypress.config.ts cypress.config.ts
COPY ./tests/cypress cypress

RUN npm install


RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  curl \
  libgtk2.0-0 \
  libgtk-3-0 \
  libgbm-dev \
  libnotify-dev \
  libgconf-2-4 \
  libnss3 \
  libxss1 \
  libasound2 \
  libxtst6 \
  xauth \
  xvfb \
  x11vnc \
  fluxbox

# Install Chrome
RUN curl https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o /tmp/google-chrome.deb
RUN apt-get install -y /tmp/google-chrome.deb

RUN Xvfb :20 -screen 0 1920x1080x16 && \
    sleep 1 && \
    x11vnc -display :20 -N -forever -bg -o "/tmp/x11vnc.log" && \
    sleep 1 && \
    DISPLAY=:20 fluxbox -log /tmp/fluxbox.log &

ENTRYPOINT ["tail", "-f", "/dev/null"   ]
